{
  "formatVersion": "1.1",
  "component": {
    "group": "org.venuspj",
    "module": "venus-ddd",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yw3svpuiufefbcn52biplpv2xi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "venus-ddd-0.0.1.jar",
          "url": "venus-ddd-0.0.1.jar",
          "size": 7103,
          "sha512": "12fd9632ed29a92bedb46af82859b1047a1af1ec5348b0bc0230b97124a0d3dc0ced04c1126ba780d41f3af1541bcdaba59470d7259c90541fe38dcd9cd88350",
          "sha256": "f8908801158736eb73211f526e58ac4394e725fbbeeca1e5870698f46488ac31",
          "sha1": "d8e7d3ae577af13cb81eee976a4ee5f1c590bb0a",
          "md5": "a8334f9757abb4e7906bf477ad12fd7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.venuspj",
          "module": "venus-utils",
          "version": {
            "requires": "1.0.13+"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.15.0+"
          }
        }
      ],
      "files": [
        {
          "name": "venus-ddd-0.0.1.jar",
          "url": "venus-ddd-0.0.1.jar",
          "size": 7103,
          "sha512": "12fd9632ed29a92bedb46af82859b1047a1af1ec5348b0bc0230b97124a0d3dc0ced04c1126ba780d41f3af1541bcdaba59470d7259c90541fe38dcd9cd88350",
          "sha256": "f8908801158736eb73211f526e58ac4394e725fbbeeca1e5870698f46488ac31",
          "sha1": "d8e7d3ae577af13cb81eee976a4ee5f1c590bb0a",
          "md5": "a8334f9757abb4e7906bf477ad12fd7f"
        }
      ]
    }
  ]
}
